# Generated by Django 5.2.4 on 2026-03-30 16:11

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Porte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Numéro de porte')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description / Localisation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Porte',
                'verbose_name_plural': 'Portes',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du Service')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Visiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('numero_cni', models.CharField(max_length=50, unique=True, verbose_name='Numéro CNIB')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10, null=True, verbose_name='Sexe')),
                ('profession', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profession')),
                ('telephone', models.CharField(max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('scan_cni_recto', models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP envy\\Desktop\\Stage\\Gestion\\private_media'), upload_to='cni_scans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Scan CNIB Recto')),
                ('scan_cni_verso', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP envy\\Desktop\\Stage\\Gestion\\private_media'), upload_to='cni_scans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Scan CNIB Verso')),
                ('date_enregistrement', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archive')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'ordering': ['-date_enregistrement'],
            },
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_entite', models.CharField(max_length=50, verbose_name="Type d'entité")),
                ('donnees_json', models.JSONField(verbose_name='Données archivées')),
                ('date_archivage', models.DateTimeField(auto_now_add=True, verbose_name="Date d'archivage")),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archives', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Archive',
                'verbose_name_plural': 'Archives',
                'ordering': ['-date_archivage'],
            },
        ),
        migrations.CreateModel(
            name='LogAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='Action')),
                ('date_heure', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('details', models.TextField(verbose_name='Détails')),
                ('entite_id', models.IntegerField(blank=True, null=True, verbose_name='ID entité')),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='Administrateur')),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
                'ordering': ['-date_heure'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('porte_actuelle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents_affectes', to='core.porte', verbose_name="Porte d'affectation")),
            ],
            options={
                'verbose_name': 'Profil Agent',
                'verbose_name_plural': 'Profils Agents',
            },
        ),
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif', models.CharField(max_length=255, verbose_name='Motif de la visite')),
                ('date_visite', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('heure_entree', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Heure d'entrée")),
                ('heure_sortie', models.DateTimeField(blank=True, null=True, verbose_name='Heure de sortie')),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('SORTI', 'Sorti')], default='PRESENT', max_length=15, verbose_name='Statut')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observations')),
                ('agent_entree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_entrees', to=settings.AUTH_USER_MODEL, verbose_name="Agent d'entrée")),
                ('agent_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visites_sorties', to=settings.AUTH_USER_MODEL, verbose_name='Agent de sortie')),
                ('porte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites', to='core.porte', verbose_name="Porte d'entrée/sortie")),
                ('service_visite', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites', to='core.service', verbose_name='Service visité')),
                ('visiteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visites', to='core.visiteur', verbose_name='Visiteur')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-heure_entree'],
            },
        ),
    ]
