# Generated by Django 5.2.4 on 2026-04-17 11:37

import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visiteur',
            name='scan_cni_recto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\HP envy\\Desktop\\Stage\\Gestion\\private_media'), upload_to='cni_scans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Scan CNIB Recto'),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone'),
        ),
    ]
