# Generated by Django 6.0.3 on 2026-04-29 11:46

import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_visiteur_scan_cni_recto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visite',
            name='porte',
        ),
        migrations.AddField(
            model_name='visite',
            name='porte_entree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visites_entrees', to='core.porte', verbose_name="Porte d'entrée"),
        ),
        migrations.AddField(
            model_name='visite',
            name='porte_sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visites_sorties', to='core.porte', verbose_name='Porte de sortie'),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='scan_cni_recto',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ousmanek\\Desktop\\STAGE\\vms1\\private_media'), upload_to='cni_scans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Scan CNIB Recto'),
        ),
        migrations.AlterField(
            model_name='visiteur',
            name='scan_cni_verso',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\ousmanek\\Desktop\\STAGE\\vms1\\private_media'), upload_to='cni_scans/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Scan CNIB Verso'),
        ),
    ]
