# Generated by Django 6.0.3 on 2026-06-21 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_agentprofile_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Est archivé'),
        ),
        migrations.AddField(
            model_name='porte',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Est archivé'),
        ),
    ]
