# Generated by Django 6.0.3 on 2026-07-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_agentprofile_is_archived_porte_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='notes_sortie',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de sortie'),
        ),
    ]
